/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cesch' at '10/15/16 11:49 PM' with Gradle 3.0
 *
 * @author cesch, @date 10/15/16 11:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
